import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Minus, Plus, Trash2, Send, UserRound } from "lucide-react";
import PageTitle from "../../components/PageTitle";
import { EVENT_TYPES, useAppData } from "../../context/AppDataContext";
import { useAuth } from "../../context/AuthContext";

const CART_KEY = "eventara_cart_v3";
const readCart = () => { try { return JSON.parse(localStorage.getItem(CART_KEY) || "[]"); } catch { return []; } };

export default function Cart() {
  const [cart, setCart] = useState(readCart);
  const { user } = useAuth();
  const { addEnquiry } = useAppData();
  const navigate = useNavigate();
  const [submitted, setSubmitted] = useState(null);
  const [form, setForm] = useState({ eventType: "marriage", eventDate: "", location: "", guests: 100, budget: "", message: "" });
  useEffect(() => { localStorage.setItem(CART_KEY, JSON.stringify(cart)); window.dispatchEvent(new Event("eventara-cart-updated")); }, [cart]);
  const total = useMemo(() => cart.reduce((sum, item) => sum + Number(item.price || 0) * Number(item.quantity || 1), 0), [cart]);
  const updateQty = (id, delta) => setCart((prev) => prev.map((item) => item.id === id ? { ...item, quantity: Math.max(1, Number(item.quantity || 1) + delta) } : item));
  const remove = (id) => setCart((prev) => prev.filter((item) => item.id !== id));
  const submit = (e) => { e.preventDefault(); if (!user) { navigate("/login", { state: { from: "/cart" } }); return; } if (!cart.length) return; const enquiry = addEnquiry({ customerId: user.id, customerName: user.name, email: user.email, phone: user.phone, ...form, guests: Number(form.guests), budget: Number(form.budget || 0), items: cart.map(({ id, name, category, serviceId, price, quantity, unit, location, contact, description }) => ({ id, name, category, serviceId, price, quantity, unit, location, contact, description })), estimatedServicesTotal: total }); localStorage.removeItem(CART_KEY); setCart([]); setSubmitted(enquiry); };
  if (submitted) return <div className="px-4 py-16 sm:px-6"><div className="mx-auto max-w-xl rounded-3xl border border-emerald-200 bg-white p-7 text-center shadow-sm"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-emerald-100 text-emerald-600"><Send /></div><h1 className="mt-4 text-2xl font-black">Enquiry submitted</h1><p className="mt-2 text-sm leading-6 text-slate-600">Thank you, {user?.name}. Your enquiry <strong>{submitted.id}</strong> is saved. The admin can now review it and contact you.</p><div className="mt-5 flex flex-col gap-2 sm:flex-row"><Link to="/my-requests" className="flex-1 rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white">View My Requests</Link><Link to="/celebrations" className="flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold">Plan Another Function</Link></div></div></div>;
  return <div className="px-4 py-10 sm:px-6 lg:px-8 lg:py-14"><PageTitle eyebrow="Your selection" title="Review and submit your enquiry" text="No online payment is required. This step simply sends your requirements to the Eventara admin team." /><div className="mx-auto mt-8 grid max-w-6xl gap-6 lg:grid-cols-[1fr_380px]">
    <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-black">Selected services</h2><span className="text-sm font-bold text-orange-600">₹{total.toLocaleString("en-IN")}</span></div>{cart.length === 0 ? <div className="py-12 text-center"><p className="font-bold text-slate-700">Your cart is empty.</p><p className="mt-1 text-sm text-slate-500">Choose services from the celebrations page.</p><Link to="/celebrations" className="mt-4 inline-flex rounded-xl bg-orange-500 px-4 py-2.5 text-sm font-bold text-white">Browse services</Link></div> : <div className="mt-5 space-y-3">{cart.map((item) => <div key={item.id} className="flex gap-3 rounded-2xl border border-slate-200 p-3"><img src={item.image} alt="" className="h-20 w-20 rounded-xl object-cover" /><div className="min-w-0 flex-1"><p className="font-bold">{item.name}</p><p className="text-xs text-slate-500">₹{Number(item.price).toLocaleString("en-IN")} • {item.unit}</p><div className="mt-2 flex items-center gap-2"><button onClick={() => updateQty(item.id, -1)} className="rounded-lg border p-1.5"><Minus className="h-3.5 w-3.5" /></button><span className="w-5 text-center text-sm font-bold">{item.quantity}</span><button onClick={() => updateQty(item.id, 1)} className="rounded-lg border p-1.5"><Plus className="h-3.5 w-3.5" /></button></div></div><button onClick={() => remove(item.id)} className="self-start rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button></div>)}</div>}</div>
    <form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-black">Function details</h2>{!user && <div className="mt-3 flex gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-800"><UserRound className="h-4 w-4 shrink-0" />Please create an account or sign in before submitting.</div>}<div className="mt-4 grid gap-3"><label className="text-xs font-bold">Function type<select value={form.eventType} onChange={(e) => setForm({ ...form, eventType: e.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">{EVENT_TYPES.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-xs font-bold">Event date<input required type="date" value={form.eventDate} onChange={(e) => setForm({ ...form, eventDate: e.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label><label className="text-xs font-bold">Location<input required value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} placeholder="Coimbatore / Chennai / Madurai..." className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">Guests<input required min="1" type="number" value={form.guests} onChange={(e) => setForm({ ...form, guests: e.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label><label className="text-xs font-bold">Budget (₹)<input type="number" min="0" value={form.budget} onChange={(e) => setForm({ ...form, budget: e.target.value })} placeholder="Optional" className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label></div><label className="text-xs font-bold">Message / special requirements<textarea value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} rows="4" placeholder="Tell us anything else you need..." className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /></label><button disabled={!cart.length} className="mt-1 inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-orange-500 to-pink-500 px-4 py-3 text-sm font-extrabold text-white disabled:cursor-not-allowed disabled:opacity-40"><Send className="h-4 w-4" />{user ? "Submit Enquiry" : "Sign in to Submit"}</button></div></form>
  </div></div>;
}
